# Generated by Django 2.1 on 2018-08-10 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20180810_0538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrol',
            new_name='Result',
        ),
        migrations.AddField(
            model_name='reg',
            name='register',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Teacher'),
        ),
    ]
