# Generated by Django 2.1 on 2018-08-10 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20180810_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Session')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='reg',
            name='course',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='session',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='result',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Registration'),
        ),
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
