# Generated by Django 2.1 on 2018-08-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_auto_20180810_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='ulogo',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
