# Generated by Django 2.1 on 2018-08-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_teacher_ulogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='ulogo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
