# Generated by Django 2.1 on 2018-08-11 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_auto_20180811_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='umob',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\0?1?\\d{11}$')]),
        ),
    ]
