# Generated by Django 2.1 on 2018-08-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_auto_20180811_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='ulogo',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='umob',
            new_name='mobile',
        ),
    ]
