# Generated by Django 2.1 on 2018-08-12 07:10

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_auto_20180811_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='reg',
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='reg', chained_model_field='course', on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Registration'),
        ),
    ]
