# Generated by Django 2.1 on 2018-09-22 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0017_auto_20180813_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='result',
            name='reg',
        ),
        migrations.AddField(
            model_name='result',
            name='avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='ct4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignation',
            name='reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Registration'),
        ),
        migrations.AddField(
            model_name='assignation',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Teacher'),
        ),
        migrations.AddField(
            model_name='result',
            name='asign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Assignation'),
        ),
    ]
